### ISSUE TITLE
[Feature] Random for animations

### ISSUE THREAD

**Issue by CrashCat** [oblivioncth/CLIFp#1]
**Is your feature request related to a problem? Please describe.**
I am enjoying using the --random parameter to launch a random game but I notice it always picks games. 

**Describe the solution you'd like**
I'd like a parameter (probably an additional one so you don't break established behavior) to play random animations instead of games, or both.

**Describe alternatives you've considered**
I can just pull up the launcher of course to get random picks across everything but I like how I can just launch a random game from a desktop shortcut using this.

**Additional context**
Bonus if there's some way to actually get to the info page on the random game/animation but I guess that's probably out of scope.  But maybe you have some advice on that.  In the launcher I could at least copy the name and search it if I want to know but since I never see the name in this command line I wouldn't know what to look at.  Maybe a parameter to get it to just spit out the name before or after launching in a message box would be nice.  Well that's more than one feature, but I am being greedy to ask for any features in the first place anyway 😄  I suppose if you like one or not the other just break out an issue for your own tracking.

**Comment by oblivioncth** [comment]
Hey, thanks for following the form.

The random mode is actually supposed to include animations. If I recall correctly, FP has a large majority of games so its possible an animation just hasn't rolled for you yet. Either way I will check to make sure the behavior you've experienced isn't a bug, and regardless I can add functionality to let you select if you want only games, animations, or both.

As for the meta data, I can't bring up Flashpoint and go to the game as I believe doesn't have an API for that and is a bit out of scope for this (though thats less of a concern); however, since the database is read to find the game, I can certainly have a quick message show up for a few seconds that shows you some of the info of the game that was selected. It is true that some games/animations never show a title so I get that it can be confusing finding one again.

I'll get to all of this when I can.

**Comment by CrashCat** [comment]
If you output the ID that you pulled in Flashpoint can I then go back and search that in Flashpoint launcher?  That would solve that part as far as I am concerned, just have another parameter for a cheap message box that prints that out, or writes the last ID to a file, or something like that.

**Comment by oblivioncth** [comment]
Honestly I like the idea of showing a few fields like the title, author, etc, but as a stop-gap solution for you specifically, the ID of the game selected is shown in CLIFp.log, though I'm not sure if you can search for entries by ID within the FP UI.

**Comment by oblivioncth** [comment]
@CrashCat 

Check out the new documentation and build and let me know if it satisfies your needs.

**Comment by oblivioncth** [comment]
Closing this under the assumption that the changes were sufficient. The issue can always be reopened if not.
