### ISSUE TITLE
Asking for ExecAction.exe and Redirect.exe?

### ISSUE THREAD

**Issue by placeboyue** [oblivioncth/CLIFp#2]
I'm not sure if it's a bug but i get "URL is wrong" messages, and it asks for "ExcecAction.exe" and "Redirect.exe" that i don't seem to have, despite having the correct versions of flashopint+CLIFp. I tried a couple games and they all give me the same message. Then it closes and i can't play.

**To Reproduce**
I do this from inside the frontend "Attract-Mode" but it shouldn't make a difference since it executes the command line parameters i order it, which were `--auto "[name]"`
Being "[name]" the way Attract-mode references to the rom filename. I created an empty .txt file with the gameID as filename, and scraped those files as if they were Roms, just to have a way to access that number easily from the frontend. I made sure it's not including the extension (.txt) by completely erasing it but it still fails.

I also made sure to put CLIPf.exe in the right folder (i tried different things and still same error) and set it as the executable in the frontend, so the error is most likely not related to the frontend, and hopefully not a human error on my side

I also tried the -i --prepare command, but a popup says that command does not exist (?!)

**Version:**
 - CLIFp version 0.4.0.1
- Flashpoint version 9.0

**Comment by placeboyue** [comment]
Apparently my flashpoint install broke, a fresh reinstall of the newer (10) version got rid of this issue and everything is working as intended, sorry.

**Comment by oblivioncth** [comment]
Sorry, you happened to catch me right as I'm in the middle of overhauling this application and I've been quite busy otherwise.

Just to clarify your issue despite it being "resolved":

1. The URL is wrong message is new to me, and I'm guessing was being created by Flashpoint software and not CLIFp. I'm curious of an example game ID you were having this issue with just so I can make sure nothing else strange is going on other than possible issue with your install as you noted
2. The -i/prepare command was added after the version you were using which is why it complained about it
3. The errors you were seeing about ExecAction.exe and Redirect.exe were due to an oversight with FP9. The dev's accidentally left entries in the web server configuration for those two executables to be ran after the game you choose is closed; however, at that point they were deprecated and removed from Flashpoint so of course they would never be found. The Flashpoint UI doesn't show an error message for failed shutdown tasks by default which is why you never saw anything when using that, but CLIFp does. During the time when FP9 was the latest the protocol was more or less to just always use the -q switch which would silence those messages.  Luckily with FP10 they finally removed the errant entries so this is no longer an issue.

In the end these details don't matter since you're up and running with the latest of each, but I figured I'd explain anyway.
