### ISSUE TITLE
[BUG] Poptropica: Error Mounting Data Pack

### ISSUE THREAD

**Issue by ForeverFloating** [oblivioncth/CLIFp#24]
**Describe the bug**
Attempting to play the game Poptropica results in the following error: "An error occurred while mounting a data pack. Operation canceled"

This issue does not seem to occur for other Flash games (tested using the command prompt: `CLIFp.exe play -r game`).

**To Reproduce**
1. Install Poptropica via Flashpoint Launcher
2. In the Flashpoint 11 Infinity folder, run the command prompt: `CLIFp.exe play -i 83e1b5e7-4282-4bbd-868e-dcfa965e4abf` or `CLIFp.exe play -t "Poptropica"`
3. See error

**Expected behavior**
The game (Poptropica) will launch.

**Version (please complete the following information):**
 - CLIFp version: 0.9.1.1
- Flashpoint version: Flashpoint 11 Infinity

**Comment by oblivioncth** [comment]
![image](https://user-images.githubusercontent.com/24661585/197375593-f7c2eca7-5c8f-4a12-aa55-7409fdda09b4.png)

*Annoyingly*, it's working on my end.

- Does the download sit at 0% for a while and then give that error, or does it happen right after seeing the progress dialog?
- Do you use a VPN, proxy, or anything like that?
- A little annoying, but you could try with a second, fresh copy of FP11 just to rule out anything strange
- Finally, could you attach a run within CLIFp.log where the issue occurred? If you don't feel like mucking about with clipping out the exact section, just try to play the game again before uploading so that the last run in the log will contain the issue, unless it's already in that state.

**Comment by ForeverFloating** [comment]
I tried reinstalling both CLIFp.exe and BlueMaxima's Flashpoint but it appears that this did not solve my issue. (I tried setting up a virtual machine to test this but I couldn't get my VM set up properly I think.) I installed CLIFp.exe by moving the .exe file to the Flashpoint 11 Infinity folder; I did not move any other files from the Github repository. I am not using a VPN. After typing the command, there is a loading bar animation for "Mounting Data Pack," and then changes to the error message. My CLIFp.log is attached in this comment.
[CLIFp.log](https://github.com/oblivioncth/CLIFp/files/9874758/CLIFp.log)

**Comment by oblivioncth** [comment]
Hmm, so the second half of the mounting process is timing out, which is really strange because it doesn't really differ on a game-by-game basis. Especially strange given it works for me, like I said.

I suppose I should have also asked the version of Windows you're using. Just trying to think of anything significant that could differ.

Give this specific build a shot and see if it works, though I'm not super hopeful as its a little bit of a shot in the dark.

https://github.com/oblivioncth/CLIFp/suites/8984555351/artifacts/413462756

**Comment by ForeverFloating** [comment]
Unfortunately the build didn't work. I tried running this command as an administrator as well just to see if it worked, which it did not. My operating system is Windows 11 Pro. My version of Windows is 10.0.22621 Build 22621.

**Comment by oblivioncth** [comment]
Here's another experiment, I set the timeout for that part of the mount to 30 seconds, which is stupidly long, but I want to see if it at least finally completes for you at some point, or simply never happens.

https://github.com/oblivioncth/CLIFp/suites/9004958659/artifacts/414911942
I threw together a VM of Windows 11 (I'm still on 10) on the latest update of build 22621, placed Flashpoint into the same location you have it, tried it there and it worked. So that at the very least is the problem.

Very strange.

**Comment by ForeverFloating** [comment]
Yes, when I run Poptropica via the regular launcher, the game runs fine. I tried the latest file of CLIFp.exe you attached in your latest comment and I am now able to run Poptropica via the command `CLIFp.exe play -t "Poptropica"`

**Comment by oblivioncth** [comment]
Ok interesting.

Please send me the latest version of your log file so I can see how long it actually took to finish mounting.

**Comment by ForeverFloating** [comment]
This is the log file: [CLIFp.log](https://github.com/oblivioncth/CLIFp/files/9891982/CLIFp.log)

**Comment by oblivioncth** [comment]
Alright well the latest release is now basically the same as that last build you tried.

Thanks for trying them out.
