### ISSUE TITLE
[BUG] Gamescope: Flash files only play audio, does not show window

### ISSUE THREAD

**Issue by jordammit** [oblivioncth/CLIFp#29]
**Describe the bug**
When running Flashpoint Linux Docker on Steam Deck, CLIFp only works under Desktop Mode (Wayland), but does not work correctly under Gaming Mode (Gamescope).   
I'm running a custom bash script to do additional work behind the scenes, but this has no bearing on the issue at hand, as adding `clifp` as a Non-Steam Shortcut with the Launch Options set as `play -i <uuid here>`  also works flawlessly in Desktop Mode, but still does not work correctly under Gaming Mode.  

As it stands currently, when launching in Gaming Mode, the audio for the loaded Flash file plays, but there is no visual component.   

**To Reproduce**
1. Installed Flashpoint and CLIFp according [to the Guide I've written](https://gist.github.com/jordammit/c6461709c43f74cba23a11e9df4fbfd4).
2. Add `clifp` as Non-Steam Game and set proper Launch Options to contain CLIFp args.
3. Attempt to launch game in Gaming Mode.
4. All sound, no visuals.

**Expected behavior**
As Gamescope obtains the window through Wayland via Xwayland, it should be expected that the launched Flash Player window should still be visible, but it is not. However, the window definitely launches, as the audio for the Flash file is present.

**Screenshots**

**Version (please complete the following information):**
 - CLIFp version: 0.9.1.2
- Flashpoint version: 11.0 "Oops! All Plugins!"

**Additional context**
I'm not totally convinced that the issue is with CLIFp myself, but it seems to be the only way I can get logs for anything Flashpoint-related being launched thru Steam (the Flashpoint GUI does not launch via Steam whether in Desktop Mode or Gaming Mode, but launches correctly when launched from the bundled `flashpoint` shell script). 

You can view said logs below, I hope this can be helpful in determining the issue:  
- [clifp.log from launch in Desktop Mode](https://gist.github.com/jordammit/0ce7fb4caa11b9f9703632d5a2e0734b) (works perfectly)
- [clifp.log from launch in Gaming Mode](https://gist.github.com/jordammit/af5349abb394c8912be147a0f51b91cc) (all sound, no visuals)

**Comment by parkerlreed** [comment]
This is not a CLIFP bug. The flash player normally through GameScope just has a block screen. We would need to file an issue over there.

**Comment by oblivioncth** [comment]
First off, I don't have a Steam Deck to test on, so anything relating to it would always be tough to try implement.

That being said, CLIFp, and the vanilla launcher for that matter, are literally just launchers. The output of all the software that actually runs the games for each platform is in no way routed through CLIFp or anything like that. The only potential influence it has on how they run is their command-line arguments, their environment variables, and to some degree how they specifically are executed with `fork()`/`execve()`.

If somehow there is a different way I can start the child processes such that their display output is more properly picked up in the scenario you've described, then I'd be happy to do so. However, I mainly only use Linux for appliances/servers and so I'm much less familiar with the more advance aspects of the desktop side of things, and have no familiarity with the innerworkings of Steam's Gaming mode or Gamescope, so I'm not really sure would what tweaks could even be attempted to work around the issue.

That being said, I think @parkerlreed is right and that chances are this is ultimately an upstream issue that I have no control over.

**Comment by jordammit** [comment]
Thanks for the replies. I kinda figured as much, but wanted to file this just in case there was anything that could be deduced from the logs. I'll go ahead and close this since the issue seems irrelevant to CLIFp itself. Thanks again!

**Comment by oblivioncth** [comment]
Funny enough the only thing out of the ordinary with your logs (other than the obvious fact you had to force terminate CLIFp when trying it in game mode) is with your run in Desktop mode.

The first note is this:
```
 - <23:56:35> [DeferredProcessManager] 'Server' ( /bin/sh | 230934 ) <stderr> [Thu Feb  2 23:56:35 2023] PHP 8.1.11 Development Server (http://172.18.0.1:22600) started
 - <23:56:35> [DeferredProcessManager] 'Daemon' ( /bin/sh | 230935 ) <stderr> docker: Error response from daemon: Conflict. The container name "/gamezip" is already in use by container "c562e6be5cf1af36994dba94fdab7226bd8f8ec1634535905e38d6797d97710b". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
which means that for whatever reason the docker container wasn't stopped from a previous run. This can happen if CLIFp is terminated early for example, though it's not actually a huge deal because as you can see it will happily use that previous instance of the container and work just fine usually.

The second is:
` - <23:56:50> [DeferredProcessManager] '' ( /bin/sh | 0 ) <stdout> Container hash: `

logging from a process with no identifier that's claiming to be PID 0, and based on it's `stdout` seems to be related to docker? Very strange. I was able to reproduce this, it only happens when re-running CLIFp after an unclean shutdown, so I'll be able to debug what that's about, though clearly it's nothing serious since everything still works.

If you eventually figure out a way to fix the root cause with Gamescope via those things I can control as mentioned earlier then feel free to re-open this. In theory it might be something I play with myself at some point, but definitely not any time soon.
