### ISSUE TITLE
[Feature] Ubuntu/Linux Version

### ISSUE THREAD

**Issue by tardigrada123** [oblivioncth/CLIFp#3]
Can you please support the Linux version of Flashpoint (at the moment in version 8.2)?
Or can you help me to write a bash script that can start a single game in the way flashpoint launches the game?
I would like to add a selection of games to my emulation frontend.
Thanks in advance

**Comment by oblivioncth** [comment]
Supporting the Linux version of Flashpoint is something that I want to do, but unfortunately at the moment it's a bit of a mess and so I'm waiting for its implementation to become a bit more organized and for some of the developmental issues to settle.

As you pointed out it's currently a few versions behind. Additionally, it runs primarily using WINE, so it's barely even a Linux version and is more so a modified Windows build. A few of its components are native, with a few more being optionally native through additional downloads. This "all over the place" state would make supporting it cumbersome and require a lot of changes to CLIFp, instead of just ones that are OS specific (i.e. file paths, system settings, admin vs sudo checks, etc). 

So it is something I'm keeping an eye on, but it just hasn't come far enough yet for the time I have to put into it.

As for writing a script... that would be quite a task. You'd essentially have to rewrite most of this program (other than the bells and whistles you don't need) as a bash script, and there's a bit more going on behind the scenes than you may realize. The script would have to rely on and parse the output of several external programs, and overall be somewhat complex.  You have to obviously start and stop different programs, but also parse JSON files, read from an SQLITE database, sometimes perform HTTPS downloads, check for the presence of and monitor the running state of one specific process, pausing for a grace period if it ends and then checking if it has restarted, and more.

It's not impossible, but there's a reason that this was written in C++ and isn't a batch script, other than just the goal of getting around the issue of hiding the console.

There's no way I'm going to take the time to basically attempt to port this to a bash script or give significant direct help with that just due to the many steps involved; however, if you really want to still try it, I can give you a high-level overview the programs flow with general (though still somewhat specific) step-by-step instructions of what you need to do to start a game, and maybe help you out with something specific incase you get stuck.

**Comment by tardigrada123** [comment]
Thank you for your detailed answer.
After your explanation  I think the best thing is to wait for a more advanced Linux Version of Flashpoint. At the moment I don't have the time (most likely also not enough knowledge) for this kind of bash script.
For now I just use a simple script that starts .swf games in fullscreen with proper controller mappings enabled - the only downside is that I can't play sidelocked games because I couldn't figure out how to use a proxy for each game. But many of the games that I wanted to add to my emulation front-end work.
So again thank you and all the best

**Comment by oblivioncth** [comment]
Yea sadly it is indeed a bit involved. At the very least it's good you have a number of the core games you care about working for other means.

The only kind of interim suggestion I can give is that since the majority of Linux Flashpoint is handled using WINE, it's entirely possible that you can use the Windows version of CLIFp with it and it will work.

I haven't used WINE in sometime so I wouldn't really be much help but I think it could be worth trying. You'd just have to place it in the folder that WINE virtualizes into the Windows hierarchy along with Flashpoint (or however else you can register Flashpoint with CLIFp in it for WINE and then invoke it using "wine cmd".

**Comment by tardigrada123** [comment]
Thanks for your suggestion, I tried CLIFp using WINE before but I only got an error messages that CLIFp doesn't appear to be in a valid Flashpoint install or that its not the matching version for Flashpoint.

**Comment by oblivioncth** [comment]
@tardigrada123 
Meant to mention that this has now been implemented for FP 11.0

**Comment by oblivioncth** [comment]
File a new issue basically just saying you request Arch support for posterity if you don't mind.

There's a decent chance it is just a few dependency issues that may be able to be worked around. Otherwise, the most prohibitive part is that GitHub actions doesn't have any Linux runners other than Ubuntu, so even if I can tweak the configuration to make the app buildable on Arch, I don't have a way to easily publish Arch builds.

I'm not against trying at least getting it to run on Arch and maybe putting up a manual build, but in the long run that may get annoying. I hope that GitHub adds other Linux runners at some point. You'd think at least a few other major ones like Fedora, CentOS, or Arch would be supported by now.

If I get really lucky with the dependencies, it may be possible to just change the Ubuntu builds so that they also work on Arch.

At the very least I'll toy with it.
